services:

  waha:
    image: devlikeapro/waha:latest
    container_name: wpp_bot_waha
    restart: always
    volumes:
      - ./.sessions:/app/.sessions
    ports:
      - '3000:3000'

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: wpp_bot_api
    ports:
      - '5000:5000'
      - '5678:5678'
    volumes:
        - './app.py:/app/app.py'
        - ./chroma_data:/app/chroma_data